name: Renovate
on:
  push:
    branches:
      - main
  # schedule:
  # - cron: '0 22 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.3.5
        with:
          configurationFile: renovate.json
          token: "${{ secrets.TOKEN }}"
#        env:
#          LOG_LEVEL: 'debug'
