name: test_merge

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
      
    - name: Build Docker image
      run: docker build -t test-image .
      
  merge:
    runs-on: ubuntu-latest
    needs: test
    if: |
      github.event.pull_request.merged == false &&
      needs.test.result == 'success'

    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          GITHUB_TOKEN: "${{ secrets.TOKEN }}"
          MERGE_LABELS: ""

          
